# i bet theres gonna be some whiny assholes complaining about this because config is .yml and not .js since most java bots use .yml and no other 
# javascript bot uses .yml, all i got to say is go cry somewhere else about it you wont change my mind, you little shit, 
# it looks cleaner than config.js - Parker2991


# FNFBoyfriendBot Config
Commands: 
  prefixes:
    -  '~'
  colors:
    discord:
      error: "#ff0000"
      embed: "#00ffff"
    help: 
      pub_lickColor: "#00FFFF"
      t_rustedColor: "dark_purple"
      own_herColor: "dark_red"
    error: "#FF0000"
 
Core: 
  JSON: ""
  area: 
    start: 
      x: 0 
      y: 0 
      z: 0
    end: 
      x: 15
      y: 0 
      z: 15

validation:
  discord: 
    roles: 
      trusted: "trusted"
      owner: "owner"
  channelId: "channel validation here"
  trustedKey: "trusted key here"
  ownerKey: "owner key here"

Discord: 
  enabled: false
  invite: "https://discord.gg/GCKtG4erux"
  commandPrefix: "!"
  presence:
    name: "amongus"
    type: 4
  status: "online"
 
console:
  filelogging: false
  prefix: "c."

bots :

  - host: "kaboom.pw"
    useChat: false
    isKaboom: true
    isCreayun: false
    usernameGen: true
    username: "FNFBoyfriendBot"
    version: "1.20.2"
    serverName: "kaboom"
    reconnectDelay: 6000
    endcredits: false
    Console:
      enabled: true
      ratelimit: 25
    Core: 
      enabled: true
      interval: 180000
    discord: 
      channelId: ""
      log: false
    matrix:
      roomId: ""
    selfcare: 
      vanished: true
      unmuted: true
      prefix: true
      cspy: true
      tptoggle: true
      skin: true
      gmc: true
      op: true
      nickname: true
      username: true
      god: true
      interval: 500